/*******************************************************************************
 * Copyright (c) 2012 Darya Filippova.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/gpl.html
 * 
 * Contributors:
 *     Darya Filippova - initial API and implementation
 ******************************************************************************/
package edu.umd.coral.ui.dialog;

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;

import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

import edu.umd.coral.ui.CoralMenu;

/**
 * Picture from Wikipedia: 
 * http://en.wikipedia.org/wiki/File:Orange_cup_coral_(Balanophyllia_elegans)_01.jpg
 * 
 * @author lynxoid
 *
 */
public class AboutDialog extends JDialog {

	private static final long serialVersionUID = -4508450055557038223L;
	
	/** Creates new form AboutDialog */
    public AboutDialog(JFrame frame) {
    	super(frame, "About Coral", true);
    	this.setPreferredSize(new Dimension(300, 230));
    	this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        JLabel jLabel2 = new JLabel();
        JLabel jLabel3 = new JLabel();
        JLabel jLabel1 = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        
        jLabel1.setIcon(new ImageIcon("edu/umd/coral/resources/coral_cropped.png")); // NOI18N
        jLabel1.addMouseListener( new MouseListener() {
			public void mouseClicked(MouseEvent e) {
				String htmlAddr = CoralMenu.CORAL_URL; // path to your new file
				try {
					URL url = new URL(htmlAddr);
					if (!Desktop.isDesktopSupported()) {
						System.out.println("Desktop operations (browsing) are not supported.");
						return;
					}
					Desktop.getDesktop().browse(url.toURI());					
				} catch (MalformedURLException e1) {
					e1.printStackTrace();
				} catch (IOException ex) {
					ex.printStackTrace();
				} catch (URISyntaxException ex) {
					ex.printStackTrace();
				}
			}
			public void mouseEntered(MouseEvent arg0) {}
			public void mouseExited(MouseEvent arg0) {}
			public void mousePressed(MouseEvent arg0) {}
			public void mouseReleased(MouseEvent arg0) {}
        });
        jLabel1.setBounds(0, 0, 300, 151);
        getContentPane().add(jLabel1);

        jLabel2.setText("<html>Darya Filippova, Aashish Gadani, Carl Kingsford</html>"); 
        jLabel2.setMaximumSize(new Dimension(100, 100));
        jLabel2.setBounds(10, 153, 280, 16); // x, y, width, height
        getContentPane().add(jLabel2);
        
        jLabel2 = new JLabel();
        jLabel2.setText("CBCB, Univesity of Maryland"); 
        jLabel2.setMaximumSize(new Dimension(100, 100));
		jLabel2.setBounds(10, 171, 280, 16); // x, y, width, height
		getContentPane().add(jLabel2);

        jLabel3.setText("2012");
        jLabel3.setBounds(10, 188, 100, 16);
        getContentPane().add(jLabel3);

        pack();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AboutDialog dialog = new AboutDialog(new JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
}
